--- 
title: 'Relación cuantitativa entre estructura y actividad '
author: "Betsaida L. Covarrubias"
date: "`r Sys.Date()`"
output: word_document
site: bookdown::bookdown_site

---

# Explorando Conceptos Clave en QSAR: Resumen del libro "Quantitative Structure–Activity Relationship" por Siavoush Dastmalchi, Maryam Hamzeh-Mivehroud y Babak Sokout

En el siguiente resumen, se abordan los conceptos clave presentes en el libro "Quantitative Structure–Activity Relationship," escrito por Siavoush Dastmalchi, Maryam Hamzeh-Mivehroud y Babak Sokout. El objetivo principal de este resumen es proporcionar una visión general de los temas fundamentales contenidos en el libro original, con un énfasis particular en la construcción de modelos QSAR (Relación Cuantitativa Estructura-Actividad).

Es importante destacar que este resumen se centra en la regresión lineal múltiple como un modelo base, ya que su simplicidad permite a los lectores familiarizarse con los conceptos fundamentales de QSAR. No obstante, el libro original, "Quantitative Structure–Activity Relationship," abarca detalles sobre una variedad de otros métodos en mayor profundidad.

Este resumen tiene un propósito educativo y de referencia, y busca simplificar y esclarecer los conceptos presentados en el libro original. Para una exploración más detallada de otros métodos y aspectos, se recomienda consultar el libro original

Los derechos de autor y la propiedad intelectual del libro original pertenecen a Siavoush Dastmalchi, Maryam Hamzeh-Mivehroud, Babak Sokout y su editorial correspondiente. Este resumen se proporciona como una herramienta para facilitar el acceso a la información contenida en el libro original y promover el entendimiento de los conceptos clave presentados en él.

Se espera que el contenido a continuación sea un punto de partida valioso para aquellos que se interesan en el campo de QSAR, especialmente para quienes no tienen una experiencia previa en el tema. Si bien este resumen no abarca todos los detalles, está diseñado para proporcionar una introducción sólida a los conceptos clave. Te alentamos a explorar más a fondo el libro original, 'Quantitative Structure–Activity Relationship,' para obtener una comprensión más completa de los métodos disponibles en este campo.
