<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Sección 8 Caso Práctico Modelo QSAR: Regresión Lineal Múltiple | Relación cuantitativa entre estructura y actividad</title>
  <meta name="description" content="Sección 8 Caso Práctico Modelo QSAR: Regresión Lineal Múltiple | Relación cuantitativa entre estructura y actividad" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Sección 8 Caso Práctico Modelo QSAR: Regresión Lineal Múltiple | Relación cuantitativa entre estructura y actividad" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Sección 8 Caso Práctico Modelo QSAR: Regresión Lineal Múltiple | Relación cuantitativa entre estructura y actividad" />
  
  
  

<meta name="author" content="Betsaida L. Covarrubias" />


<meta name="date" content="2023-09-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="validación-del-modelo-qsar.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bitácora de Avances SSP</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Explorando Conceptos Clave en QSAR: Resumen del libro “Quantitative Structure–Activity Relationship” por Siavoush Dastmalchi, Maryam Hamzeh-Mivehroud y Babak Sokout</a></li>
<li class="chapter" data-level="2" data-path="relación-cuantitativa-entre-estructura-y-actividad.html"><a href="relación-cuantitativa-entre-estructura-y-actividad.html"><i class="fa fa-check"></i><b>2</b> Relación cuantitativa entre estructura y actividad</a></li>
<li class="chapter" data-level="3" data-path="datos.html"><a href="datos.html"><i class="fa fa-check"></i><b>3</b> Datos</a></li>
<li class="chapter" data-level="4" data-path="descriptores-moleculares.html"><a href="descriptores-moleculares.html"><i class="fa fa-check"></i><b>4</b> Descriptores moleculares</a></li>
<li class="chapter" data-level="5" data-path="selección-de-descriptores.html"><a href="selección-de-descriptores.html"><i class="fa fa-check"></i><b>5</b> Selección de descriptores</a></li>
<li class="chapter" data-level="6" data-path="construcción-del-modelo.html"><a href="construcción-del-modelo.html"><i class="fa fa-check"></i><b>6</b> Construcción del modelo</a></li>
<li class="chapter" data-level="7" data-path="validación-del-modelo-qsar.html"><a href="validación-del-modelo-qsar.html"><i class="fa fa-check"></i><b>7</b> Validación del modelo QSAR</a></li>
<li class="chapter" data-level="8" data-path="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html"><i class="fa fa-check"></i><b>8</b> Caso Práctico Modelo QSAR: Regresión Lineal Múltiple</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con GitHub</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Relación cuantitativa entre estructura y actividad</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="caso-práctico-modelo-qsar-regresión-lineal-múltiple" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Sección 8</span> Caso Práctico Modelo QSAR: Regresión Lineal Múltiple<a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#caso-práctico-modelo-qsar-regresión-lineal-múltiple" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Este caso práctico se enfoca en la construcción de un modelo QSAR (Análisis Cuantitativo de Relación Estructura-Actividad) mediante regresión lineal múltiple (MLR). Los datos de partida se obtuvieron del artículo titulado “QSAR Study of (5-Nitroheteroaryl-1,3,4-Thiadiazole-2-yl) Piperazinyl Derivatives to Predict New Similar Compounds as Antileishmanial Agents” (1). En dicho artículo, se llevaron a cabo estudios QSAR que incluyeron análisis de componentes principales (PCA), regresión lineal múltiple (MLR), regresión no lineal (RNLM) y cálculos de redes neuronales artificiales (ANN) en una serie de 36 compuestos derivados de (5-Nitroheteroaryl-1,3,4-Thiadiazole-2-yl) Piperazinyl (2). El objetivo principal era identificar las características estructurales clave necesarias para diseñar nuevos candidatos potentes de esta clase para la actividad antileishmanial.</p>
<p>En este caso práctico, nos proponemos comparar los resultados obtenidos en nuestro ejercicio con los del mencionado artículo, centrándonos específicamente en el método de regresión lineal múltiple.</p>
<p>La estructura de este caso práctico se dividirá en las siguientes secciones: recopilación de datos, descripción de descriptores moleculares, selección de descriptores, construcción del modelo y validación del modelo.</p>
<p>A diferencia del artículo de referencia, implementaremos el desarrollo del modelo utilizando Rstudio en lugar de XLSTAT versión 2013 que se utilizaron para predecir los efectos sobre la actividad antileishmania.</p>
<p><strong>Datos</strong></p>
<ul>
<li>Fuente de datos</li>
</ul>
<p>La información sobre la actividad antileishmanial experimental (<span class="math inline">\(pIC_{50}\)</span> en μM) de 36 derivados de tiadiazol se ha recopilado de un estudio previo (2). Cabe destacar que los valores de <span class="math inline">\(pIC_{50}\)</span> para las 30 moléculas que componen el conjunto de entrenamiento del modelo oscilan en un rango que va desde 3,155 y 5,046. Los detalles sobre las moléculas y sus respectivas actividades biológicas calculadas experimentalmente (<span class="math inline">\(pIC_{50}\)</span>) se presentan en la siguiente tabla.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-3" tabindex="-1"></a></span>
<span id="cb1-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-4" tabindex="-1"></a><span class="co"># Cargar datos</span></span>
<span id="cb1-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-5" tabindex="-1"></a>Valores_pIC50_Tiadiazoles <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">&quot;Valores_pIC50_Tiadiazoles.xlsx&quot;</span>)</span>
<span id="cb1-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-6" tabindex="-1"></a></span>
<span id="cb1-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-7" tabindex="-1"></a><span class="co"># Dividir el conjunto de datos en partes y mostrarlo en una tabla</span></span>
<span id="cb1-8"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-8" tabindex="-1"></a>partes <span class="ot">&lt;-</span> <span class="fu">split</span>(Valores_pIC50_Tiadiazoles, <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ceiling</span>(<span class="fu">nrow</span>(Valores_pIC50_Tiadiazoles) <span class="sc">/</span> <span class="dv">9</span>), <span class="at">each =</span> <span class="dv">9</span>, <span class="at">length.out =</span> <span class="fu">nrow</span>(Valores_pIC50_Tiadiazoles)))</span>
<span id="cb1-9"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-9" tabindex="-1"></a>tabla_datos <span class="ot">&lt;-</span> <span class="fu">do.call</span>(cbind, partes)</span>
<span id="cb1-10"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb1-10" tabindex="-1"></a><span class="fu">kable</span>(tabla_datos)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">1.N</th>
<th align="right">1.pIC50</th>
<th align="left">2.N</th>
<th align="right">2.pIC50</th>
<th align="left">3.N</th>
<th align="right">3.pIC50</th>
<th align="left">4.N</th>
<th align="right">4.pIC50</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="right">4.932</td>
<td align="left">10*</td>
<td align="right">4.222</td>
<td align="left">19</td>
<td align="right">4.592</td>
<td align="left">28</td>
<td align="right">4.482</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="right">4.969</td>
<td align="left">11*</td>
<td align="right">4.618</td>
<td align="left">20</td>
<td align="right">5.029</td>
<td align="left">29</td>
<td align="right">5.046</td>
</tr>
<tr class="odd">
<td align="left">3*</td>
<td align="right">4.880</td>
<td align="left">12</td>
<td align="right">4.549</td>
<td align="left">21</td>
<td align="right">4.797</td>
<td align="left">30</td>
<td align="right">4.100</td>
</tr>
<tr class="even">
<td align="left">4*</td>
<td align="right">4.581</td>
<td align="left">13</td>
<td align="right">4.624</td>
<td align="left">22</td>
<td align="right">3.983</td>
<td align="left">31</td>
<td align="right">4.022</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="right">4.717</td>
<td align="left">14</td>
<td align="right">4.608</td>
<td align="left">23</td>
<td align="right">3.955</td>
<td align="left">32</td>
<td align="right">4.032</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="right">4.921</td>
<td align="left">15</td>
<td align="right">4.983</td>
<td align="left">24</td>
<td align="right">4.638</td>
<td align="left">33</td>
<td align="right">3.155</td>
</tr>
<tr class="odd">
<td align="left">7</td>
<td align="right">4.882</td>
<td align="left">16</td>
<td align="right">4.693</td>
<td align="left">25</td>
<td align="right">4.482</td>
<td align="left">34</td>
<td align="right">3.222</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="right">4.602</td>
<td align="left">17*</td>
<td align="right">4.748</td>
<td align="left">26</td>
<td align="right">5.000</td>
<td align="left">35</td>
<td align="right">4.143</td>
</tr>
<tr class="odd">
<td align="left">9</td>
<td align="right">4.463</td>
<td align="left">18*</td>
<td align="right">4.367</td>
<td align="left">27</td>
<td align="right">4.959</td>
<td align="left">36</td>
<td align="right">4.319</td>
</tr>
</tbody>
</table>
<p><strong>Descriptores moleculares</strong></p>
<ul>
<li>Generación de descriptores</li>
</ul>
<p>Para calcular los descriptores electrónicos, los autores emplearon el paquete Gaussian03W (3). Las geometrías de los 36 derivados de tiadiazol se optimizaron mediante el método DFT (Teoría del Funcional de Densidad), una técnica teórica en química computacional utilizada para calcular propiedades electrónicas de las moléculas. Estos cálculos se realizaron utilizando el conjunto funcional B3LYP, que define las interacciones electrónicas en las moléculas, y la base 6-31G (d), un conjunto de funciones de base utilizado para aproximar las funciones de onda electrónica en los cálculos de DFT. Estos cálculos proporcionaron varios descriptores estructurales clave, incluyendo la energía orbital molecular ocupada más alta (HOMO), la energía orbital molecular desocupada más baja (LUMO), el momento dipolar (μ), la brecha de energía (ΔE) y la energía total.</p>
<p>Por otro lado, para calcular una serie de descriptores moleculares adicionales, como el volumen molar MV (cm³), el peso molecular MW (g/mol), la refractividad molar MR (cm³), el parachor Pc (cm³), la densidad D (g/cm³), el índice de refracción n y el coeficiente de partición octanol/agua (logP), se utilizó el programa ChemSketch (4). Los valores de los 12 descriptores químicos calculados se presentan en la siguiente tabla.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb2-1" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb2-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb2-2" tabindex="-1"></a></span>
<span id="cb2-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb2-3" tabindex="-1"></a><span class="co"># Cargar datos</span></span>
<span id="cb2-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb2-4" tabindex="-1"></a>Valores_Parametros_Tiadiazoles <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">&quot;Valores_Parametros_Tiadiazoles.xlsx&quot;</span>)</span>
<span id="cb2-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb2-5" tabindex="-1"></a></span>
<span id="cb2-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb2-6" tabindex="-1"></a><span class="co"># Mostrar datos</span></span>
<span id="cb2-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb2-7" tabindex="-1"></a><span class="fu">kable</span>(Valores_Parametros_Tiadiazoles, <span class="at">format =</span> <span class="st">&quot;html&quot;</span>, <span class="at">table.attr =</span> <span class="st">&#39;style=&quot;font-size: 69%;&quot;&#39;</span>)</span></code></pre></div>
<table style="font-size: 69%;">
<thead>
<tr>
<th style="text-align:left;">
N
</th>
<th style="text-align:right;">
pIC50
</th>
<th style="text-align:right;">
MW
</th>
<th style="text-align:right;">
MR
</th>
<th style="text-align:right;">
MV
</th>
<th style="text-align:right;">
Pc
</th>
<th style="text-align:right;">
nn
</th>
<th style="text-align:right;">
D
</th>
<th style="text-align:right;">
Et
</th>
<th style="text-align:right;">
Ehomo
</th>
<th style="text-align:right;">
Elumo
</th>
<th style="text-align:right;">
ΔE
</th>
<th style="text-align:right;">
µµ
</th>
<th style="text-align:right;">
logP
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
4.932
</td>
<td style="text-align:right;">
385.40
</td>
<td style="text-align:right;">
97.67
</td>
<td style="text-align:right;">
265.6
</td>
<td style="text-align:right;">
36.597
</td>
<td style="text-align:right;">
1.66
</td>
<td style="text-align:right;">
1.45
</td>
<td style="text-align:right;">
-44404.76
</td>
<td style="text-align:right;">
-6.59
</td>
<td style="text-align:right;">
-2.84
</td>
<td style="text-align:right;">
3.75
</td>
<td style="text-align:right;">
3.04
</td>
<td style="text-align:right;">
1.844
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
4.969
</td>
<td style="text-align:right;">
419.84
</td>
<td style="text-align:right;">
102.56
</td>
<td style="text-align:right;">
277.5
</td>
<td style="text-align:right;">
34.399
</td>
<td style="text-align:right;">
1.66
</td>
<td style="text-align:right;">
1.51
</td>
<td style="text-align:right;">
-56919.44
</td>
<td style="text-align:right;">
-6.70
</td>
<td style="text-align:right;">
-2.85
</td>
<td style="text-align:right;">
3.85
</td>
<td style="text-align:right;">
3.77
</td>
<td style="text-align:right;">
2.402
</td>
</tr>
<tr>
<td style="text-align:left;">
3*
</td>
<td style="text-align:right;">
4.880
</td>
<td style="text-align:right;">
419.84
</td>
<td style="text-align:right;">
102.56
</td>
<td style="text-align:right;">
277.5
</td>
<td style="text-align:right;">
34.399
</td>
<td style="text-align:right;">
1.66
</td>
<td style="text-align:right;">
1.51
</td>
<td style="text-align:right;">
-56919.28
</td>
<td style="text-align:right;">
-6.41
</td>
<td style="text-align:right;">
-2.92
</td>
<td style="text-align:right;">
3.49
</td>
<td style="text-align:right;">
5.40
</td>
<td style="text-align:right;">
2.402
</td>
</tr>
<tr>
<td style="text-align:left;">
4*
</td>
<td style="text-align:right;">
4.581
</td>
<td style="text-align:right;">
419.84
</td>
<td style="text-align:right;">
102.56
</td>
<td style="text-align:right;">
277.5
</td>
<td style="text-align:right;">
34.399
</td>
<td style="text-align:right;">
1.66
</td>
<td style="text-align:right;">
1.51
</td>
<td style="text-align:right;">
-56919.54
</td>
<td style="text-align:right;">
-6.69
</td>
<td style="text-align:right;">
-2.88
</td>
<td style="text-align:right;">
3.82
</td>
<td style="text-align:right;">
2.20
</td>
<td style="text-align:right;">
2.402
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:right;">
4.717
</td>
<td style="text-align:right;">
391.42
</td>
<td style="text-align:right;">
96.05
</td>
<td style="text-align:right;">
255.1
</td>
<td style="text-align:right;">
42.830
</td>
<td style="text-align:right;">
1.68
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
-53138.85
</td>
<td style="text-align:right;">
-6.38
</td>
<td style="text-align:right;">
-3.08
</td>
<td style="text-align:right;">
3.30
</td>
<td style="text-align:right;">
7.55
</td>
<td style="text-align:right;">
1.825
</td>
</tr>
<tr>
<td style="text-align:left;">
6
</td>
<td style="text-align:right;">
4.921
</td>
<td style="text-align:right;">
425.87
</td>
<td style="text-align:right;">
100.95
</td>
<td style="text-align:right;">
267.0
</td>
<td style="text-align:right;">
40.057
</td>
<td style="text-align:right;">
1.68
</td>
<td style="text-align:right;">
1.59
</td>
<td style="text-align:right;">
-65653.52
</td>
<td style="text-align:right;">
-6.70
</td>
<td style="text-align:right;">
-2.88
</td>
<td style="text-align:right;">
3.82
</td>
<td style="text-align:right;">
5.74
</td>
<td style="text-align:right;">
2.199
</td>
</tr>
<tr>
<td style="text-align:left;">
7
</td>
<td style="text-align:right;">
4.882
</td>
<td style="text-align:right;">
470.32
</td>
<td style="text-align:right;">
103.74
</td>
<td style="text-align:right;">
271.2
</td>
<td style="text-align:right;">
46.026
</td>
<td style="text-align:right;">
1.69
</td>
<td style="text-align:right;">
1.73
</td>
<td style="text-align:right;">
-123149.92
</td>
<td style="text-align:right;">
-6.65
</td>
<td style="text-align:right;">
-2.87
</td>
<td style="text-align:right;">
3.78
</td>
<td style="text-align:right;">
6.74
</td>
<td style="text-align:right;">
2.534
</td>
</tr>
<tr>
<td style="text-align:left;">
8
</td>
<td style="text-align:right;">
4.602
</td>
<td style="text-align:right;">
401.46
</td>
<td style="text-align:right;">
103.75
</td>
<td style="text-align:right;">
272.3
</td>
<td style="text-align:right;">
36.730
</td>
<td style="text-align:right;">
1.69
</td>
<td style="text-align:right;">
1.47
</td>
<td style="text-align:right;">
-53199.45
</td>
<td style="text-align:right;">
-6.37
</td>
<td style="text-align:right;">
-2.48
</td>
<td style="text-align:right;">
3.89
</td>
<td style="text-align:right;">
3.56
</td>
<td style="text-align:right;">
3.210
</td>
</tr>
<tr>
<td style="text-align:left;">
9
</td>
<td style="text-align:right;">
4.463
</td>
<td style="text-align:right;">
435.91
</td>
<td style="text-align:right;">
108.65
</td>
<td style="text-align:right;">
284.2
</td>
<td style="text-align:right;">
34.520
</td>
<td style="text-align:right;">
1.69
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
-65714.15
</td>
<td style="text-align:right;">
-6.69
</td>
<td style="text-align:right;">
-2.93
</td>
<td style="text-align:right;">
3.76
</td>
<td style="text-align:right;">
6.05
</td>
<td style="text-align:right;">
3.768
</td>
</tr>
<tr>
<td style="text-align:left;">
10*
</td>
<td style="text-align:right;">
4.222
</td>
<td style="text-align:right;">
435.91
</td>
<td style="text-align:right;">
108.65
</td>
<td style="text-align:right;">
284.2
</td>
<td style="text-align:right;">
34.520
</td>
<td style="text-align:right;">
1.69
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
-65714.24
</td>
<td style="text-align:right;">
-6.70
</td>
<td style="text-align:right;">
-2.96
</td>
<td style="text-align:right;">
3.74
</td>
<td style="text-align:right;">
5.57
</td>
<td style="text-align:right;">
3.768
</td>
</tr>
<tr>
<td style="text-align:left;">
11*
</td>
<td style="text-align:right;">
4.618
</td>
<td style="text-align:right;">
435.91
</td>
<td style="text-align:right;">
108.65
</td>
<td style="text-align:right;">
284.2
</td>
<td style="text-align:right;">
34.520
</td>
<td style="text-align:right;">
1.69
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
-65714.25
</td>
<td style="text-align:right;">
-6.70
</td>
<td style="text-align:right;">
-2.97
</td>
<td style="text-align:right;">
3.73
</td>
<td style="text-align:right;">
4.39
</td>
<td style="text-align:right;">
3.768
</td>
</tr>
<tr>
<td style="text-align:left;">
12
</td>
<td style="text-align:right;">
4.549
</td>
<td style="text-align:right;">
407.49
</td>
<td style="text-align:right;">
102.14
</td>
<td style="text-align:right;">
261.7
</td>
<td style="text-align:right;">
42.999
</td>
<td style="text-align:right;">
1.71
</td>
<td style="text-align:right;">
1.56
</td>
<td style="text-align:right;">
-61933.62
</td>
<td style="text-align:right;">
-6.61
</td>
<td style="text-align:right;">
-2.93
</td>
<td style="text-align:right;">
3.69
</td>
<td style="text-align:right;">
6.03
</td>
<td style="text-align:right;">
3.191
</td>
</tr>
<tr>
<td style="text-align:left;">
13
</td>
<td style="text-align:right;">
4.624
</td>
<td style="text-align:right;">
441.94
</td>
<td style="text-align:right;">
107.03
</td>
<td style="text-align:right;">
273.7
</td>
<td style="text-align:right;">
40.210
</td>
<td style="text-align:right;">
1.71
</td>
<td style="text-align:right;">
1.61
</td>
<td style="text-align:right;">
-74448.23
</td>
<td style="text-align:right;">
-6.68
</td>
<td style="text-align:right;">
-2.96
</td>
<td style="text-align:right;">
3.72
</td>
<td style="text-align:right;">
5.14
</td>
<td style="text-align:right;">
3.565
</td>
</tr>
<tr>
<td style="text-align:left;">
14
</td>
<td style="text-align:right;">
4.608
</td>
<td style="text-align:right;">
486.39
</td>
<td style="text-align:right;">
109.83
</td>
<td style="text-align:right;">
277.9
</td>
<td style="text-align:right;">
46.214
</td>
<td style="text-align:right;">
1.72
</td>
<td style="text-align:right;">
1.75
</td>
<td style="text-align:right;">
-131944.63
</td>
<td style="text-align:right;">
-6.65
</td>
<td style="text-align:right;">
-2.96
</td>
<td style="text-align:right;">
3.69
</td>
<td style="text-align:right;">
5.21
</td>
<td style="text-align:right;">
3.900
</td>
</tr>
<tr>
<td style="text-align:left;">
15
</td>
<td style="text-align:right;">
4.983
</td>
<td style="text-align:right;">
399.43
</td>
<td style="text-align:right;">
105.86
</td>
<td style="text-align:right;">
254.8
</td>
<td style="text-align:right;">
37.730
</td>
<td style="text-align:right;">
1.77
</td>
<td style="text-align:right;">
1.56
</td>
<td style="text-align:right;">
-45371.46
</td>
<td style="text-align:right;">
-6.25
</td>
<td style="text-align:right;">
-2.81
</td>
<td style="text-align:right;">
3.44
</td>
<td style="text-align:right;">
5.62
</td>
<td style="text-align:right;">
3.856
</td>
</tr>
<tr>
<td style="text-align:left;">
16
</td>
<td style="text-align:right;">
4.693
</td>
<td style="text-align:right;">
433.87
</td>
<td style="text-align:right;">
110.46
</td>
<td style="text-align:right;">
264.1
</td>
<td style="text-align:right;">
35.430
</td>
<td style="text-align:right;">
1.78
</td>
<td style="text-align:right;">
1.64
</td>
<td style="text-align:right;">
-57886.14
</td>
<td style="text-align:right;">
-6.32
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
3.50
</td>
<td style="text-align:right;">
5.92
</td>
<td style="text-align:right;">
3.039
</td>
</tr>
<tr>
<td style="text-align:left;">
17*
</td>
<td style="text-align:right;">
4.748
</td>
<td style="text-align:right;">
433.87
</td>
<td style="text-align:right;">
110.46
</td>
<td style="text-align:right;">
264.1
</td>
<td style="text-align:right;">
35.430
</td>
<td style="text-align:right;">
1.78
</td>
<td style="text-align:right;">
1.64
</td>
<td style="text-align:right;">
-57886.23
</td>
<td style="text-align:right;">
-6.35
</td>
<td style="text-align:right;">
-2.86
</td>
<td style="text-align:right;">
3.49
</td>
<td style="text-align:right;">
4.92
</td>
<td style="text-align:right;">
2.825
</td>
</tr>
<tr>
<td style="text-align:left;">
18*
</td>
<td style="text-align:right;">
4.367
</td>
<td style="text-align:right;">
433.87
</td>
<td style="text-align:right;">
110.46
</td>
<td style="text-align:right;">
264.1
</td>
<td style="text-align:right;">
35.430
</td>
<td style="text-align:right;">
1.78
</td>
<td style="text-align:right;">
1.64
</td>
<td style="text-align:right;">
-57886.24
</td>
<td style="text-align:right;">
-6.40
</td>
<td style="text-align:right;">
-2.72
</td>
<td style="text-align:right;">
3.68
</td>
<td style="text-align:right;">
3.96
</td>
<td style="text-align:right;">
3.956
</td>
</tr>
<tr>
<td style="text-align:left;">
19
</td>
<td style="text-align:right;">
4.592
</td>
<td style="text-align:right;">
405.45
</td>
<td style="text-align:right;">
104.45
</td>
<td style="text-align:right;">
237.2
</td>
<td style="text-align:right;">
44.267
</td>
<td style="text-align:right;">
1.83
</td>
<td style="text-align:right;">
1.70
</td>
<td style="text-align:right;">
-54105.54
</td>
<td style="text-align:right;">
-6.35
</td>
<td style="text-align:right;">
-2.87
</td>
<td style="text-align:right;">
3.49
</td>
<td style="text-align:right;">
5.42
</td>
<td style="text-align:right;">
3.756
</td>
</tr>
<tr>
<td style="text-align:left;">
20
</td>
<td style="text-align:right;">
5.029
</td>
<td style="text-align:right;">
439.90
</td>
<td style="text-align:right;">
109.05
</td>
<td style="text-align:right;">
246.5
</td>
<td style="text-align:right;">
41.356
</td>
<td style="text-align:right;">
1.84
</td>
<td style="text-align:right;">
1.78
</td>
<td style="text-align:right;">
-66620.16
</td>
<td style="text-align:right;">
-5.81
</td>
<td style="text-align:right;">
-1.95
</td>
<td style="text-align:right;">
3.86
</td>
<td style="text-align:right;">
6.30
</td>
<td style="text-align:right;">
2.956
</td>
</tr>
<tr>
<td style="text-align:left;">
21
</td>
<td style="text-align:right;">
4.797
</td>
<td style="text-align:right;">
484.35
</td>
<td style="text-align:right;">
112.01
</td>
<td style="text-align:right;">
249.7
</td>
<td style="text-align:right;">
47.628
</td>
<td style="text-align:right;">
1.85
</td>
<td style="text-align:right;">
1.93
</td>
<td style="text-align:right;">
-124116.56
</td>
<td style="text-align:right;">
-6.42
</td>
<td style="text-align:right;">
-2.90
</td>
<td style="text-align:right;">
3.52
</td>
<td style="text-align:right;">
4.48
</td>
<td style="text-align:right;">
2.984
</td>
</tr>
<tr>
<td style="text-align:left;">
22
</td>
<td style="text-align:right;">
3.983
</td>
<td style="text-align:right;">
382.40
</td>
<td style="text-align:right;">
97.23
</td>
<td style="text-align:right;">
247.9
</td>
<td style="text-align:right;">
32.430
</td>
<td style="text-align:right;">
1.71
</td>
<td style="text-align:right;">
1.54
</td>
<td style="text-align:right;">
-43830.08
</td>
<td style="text-align:right;">
-6.25
</td>
<td style="text-align:right;">
-2.94
</td>
<td style="text-align:right;">
3.31
</td>
<td style="text-align:right;">
2.15
</td>
<td style="text-align:right;">
2.784
</td>
</tr>
<tr>
<td style="text-align:left;">
23
</td>
<td style="text-align:right;">
3.955
</td>
<td style="text-align:right;">
399.42
</td>
<td style="text-align:right;">
103.40
</td>
<td style="text-align:right;">
243.0
</td>
<td style="text-align:right;">
32.209
</td>
<td style="text-align:right;">
1.80
</td>
<td style="text-align:right;">
1.64
</td>
<td style="text-align:right;">
-45370.34
</td>
<td style="text-align:right;">
-5.75
</td>
<td style="text-align:right;">
-2.84
</td>
<td style="text-align:right;">
2.91
</td>
<td style="text-align:right;">
8.11
</td>
<td style="text-align:right;">
1.894
</td>
</tr>
<tr>
<td style="text-align:left;">
24
</td>
<td style="text-align:right;">
4.638
</td>
<td style="text-align:right;">
413.45
</td>
<td style="text-align:right;">
108.96
</td>
<td style="text-align:right;">
266.1
</td>
<td style="text-align:right;">
27.642
</td>
<td style="text-align:right;">
1.76
</td>
<td style="text-align:right;">
1.55
</td>
<td style="text-align:right;">
-46440.57
</td>
<td style="text-align:right;">
-5.75
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
2.94
</td>
<td style="text-align:right;">
7.46
</td>
<td style="text-align:right;">
2.414
</td>
</tr>
<tr>
<td style="text-align:left;">
25
</td>
<td style="text-align:right;">
4.482
</td>
<td style="text-align:right;">
427.48
</td>
<td style="text-align:right;">
113.57
</td>
<td style="text-align:right;">
282.1
</td>
<td style="text-align:right;">
25.050
</td>
<td style="text-align:right;">
1.74
</td>
<td style="text-align:right;">
1.51
</td>
<td style="text-align:right;">
-47511.32
</td>
<td style="text-align:right;">
-5.73
</td>
<td style="text-align:right;">
-2.80
</td>
<td style="text-align:right;">
2.93
</td>
<td style="text-align:right;">
8.00
</td>
<td style="text-align:right;">
2.753
</td>
</tr>
<tr>
<td style="text-align:left;">
26
</td>
<td style="text-align:right;">
5.000
</td>
<td style="text-align:right;">
441.51
</td>
<td style="text-align:right;">
118.18
</td>
<td style="text-align:right;">
298.2
</td>
<td style="text-align:right;">
22.805
</td>
<td style="text-align:right;">
1.72
</td>
<td style="text-align:right;">
1.48
</td>
<td style="text-align:right;">
-48581.84
</td>
<td style="text-align:right;">
-5.73
</td>
<td style="text-align:right;">
-2.12
</td>
<td style="text-align:right;">
3.60
</td>
<td style="text-align:right;">
7.38
</td>
<td style="text-align:right;">
3.239
</td>
</tr>
<tr>
<td style="text-align:left;">
27
</td>
<td style="text-align:right;">
4.959
</td>
<td style="text-align:right;">
455.53
</td>
<td style="text-align:right;">
122.79
</td>
<td style="text-align:right;">
314.2
</td>
<td style="text-align:right;">
20.850
</td>
<td style="text-align:right;">
1.71
</td>
<td style="text-align:right;">
1.44
</td>
<td style="text-align:right;">
-49652.19
</td>
<td style="text-align:right;">
-5.71
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
2.89
</td>
<td style="text-align:right;">
7.61
</td>
<td style="text-align:right;">
3.656
</td>
</tr>
<tr>
<td style="text-align:left;">
28
</td>
<td style="text-align:right;">
4.482
</td>
<td style="text-align:right;">
455.53
</td>
<td style="text-align:right;">
122.95
</td>
<td style="text-align:right;">
317.9
</td>
<td style="text-align:right;">
21.003
</td>
<td style="text-align:right;">
1.70
</td>
<td style="text-align:right;">
1.43
</td>
<td style="text-align:right;">
-49652.25
</td>
<td style="text-align:right;">
-5.20
</td>
<td style="text-align:right;">
-1.92
</td>
<td style="text-align:right;">
3.27
</td>
<td style="text-align:right;">
9.94
</td>
<td style="text-align:right;">
3.557
</td>
</tr>
<tr>
<td style="text-align:left;">
29
</td>
<td style="text-align:right;">
5.046
</td>
<td style="text-align:right;">
489.55
</td>
<td style="text-align:right;">
134.26
</td>
<td style="text-align:right;">
334.7
</td>
<td style="text-align:right;">
21.693
</td>
<td style="text-align:right;">
1.73
</td>
<td style="text-align:right;">
1.46
</td>
<td style="text-align:right;">
-52732.28
</td>
<td style="text-align:right;">
-5.73
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
2.91
</td>
<td style="text-align:right;">
7.91
</td>
<td style="text-align:right;">
4.288
</td>
</tr>
<tr>
<td style="text-align:left;">
30
</td>
<td style="text-align:right;">
4.100
</td>
<td style="text-align:right;">
519.58
</td>
<td style="text-align:right;">
140.07
</td>
<td style="text-align:right;">
356.3
</td>
<td style="text-align:right;">
19.321
</td>
<td style="text-align:right;">
1.72
</td>
<td style="text-align:right;">
1.45
</td>
<td style="text-align:right;">
-55850.74
</td>
<td style="text-align:right;">
-5.72
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
2.90
</td>
<td style="text-align:right;">
7.84
</td>
<td style="text-align:right;">
4.162
</td>
</tr>
<tr>
<td style="text-align:left;">
31
</td>
<td style="text-align:right;">
4.022
</td>
<td style="text-align:right;">
483.54
</td>
<td style="text-align:right;">
126.43
</td>
<td style="text-align:right;">
309.1
</td>
<td style="text-align:right;">
22.355
</td>
<td style="text-align:right;">
1.75
</td>
<td style="text-align:right;">
1.56
</td>
<td style="text-align:right;">
-52737.79
</td>
<td style="text-align:right;">
-5.76
</td>
<td style="text-align:right;">
-2.83
</td>
<td style="text-align:right;">
2.92
</td>
<td style="text-align:right;">
7.31
</td>
<td style="text-align:right;">
2.555
</td>
</tr>
<tr>
<td style="text-align:left;">
32
</td>
<td style="text-align:right;">
4.032
</td>
<td style="text-align:right;">
469.52
</td>
<td style="text-align:right;">
122.72
</td>
<td style="text-align:right;">
299.1
</td>
<td style="text-align:right;">
24.975
</td>
<td style="text-align:right;">
1.76
</td>
<td style="text-align:right;">
1.56
</td>
<td style="text-align:right;">
-51666.81
</td>
<td style="text-align:right;">
-5.77
</td>
<td style="text-align:right;">
-2.83
</td>
<td style="text-align:right;">
2.94
</td>
<td style="text-align:right;">
7.35
</td>
<td style="text-align:right;">
2.392
</td>
</tr>
<tr>
<td style="text-align:left;">
33
</td>
<td style="text-align:right;">
3.155
</td>
<td style="text-align:right;">
425.46
</td>
<td style="text-align:right;">
112.35
</td>
<td style="text-align:right;">
262.4
</td>
<td style="text-align:right;">
34.888
</td>
<td style="text-align:right;">
1.80
</td>
<td style="text-align:right;">
1.62
</td>
<td style="text-align:right;">
-47478.41
</td>
<td style="text-align:right;">
-5.42
</td>
<td style="text-align:right;">
-3.00
</td>
<td style="text-align:right;">
2.42
</td>
<td style="text-align:right;">
5.80
</td>
<td style="text-align:right;">
0.821
</td>
</tr>
<tr>
<td style="text-align:left;">
34
</td>
<td style="text-align:right;">
3.222
</td>
<td style="text-align:right;">
439.49
</td>
<td style="text-align:right;">
116.96
</td>
<td style="text-align:right;">
278.5
</td>
<td style="text-align:right;">
32.136
</td>
<td style="text-align:right;">
1.78
</td>
<td style="text-align:right;">
1.57
</td>
<td style="text-align:right;">
-48548.98
</td>
<td style="text-align:right;">
-5.57
</td>
<td style="text-align:right;">
-2.81
</td>
<td style="text-align:right;">
2.76
</td>
<td style="text-align:right;">
8.18
</td>
<td style="text-align:right;">
0.927
</td>
</tr>
<tr>
<td style="text-align:left;">
35
</td>
<td style="text-align:right;">
4.143
</td>
<td style="text-align:right;">
436.28
</td>
<td style="text-align:right;">
100.16
</td>
<td style="text-align:right;">
268.9
</td>
<td style="text-align:right;">
40.777
</td>
<td style="text-align:right;">
1.67
</td>
<td style="text-align:right;">
1.62
</td>
<td style="text-align:right;">
-111329.43
</td>
<td style="text-align:right;">
-5.92
</td>
<td style="text-align:right;">
-2.86
</td>
<td style="text-align:right;">
3.06
</td>
<td style="text-align:right;">
5.18
</td>
<td style="text-align:right;">
3.579
</td>
</tr>
<tr>
<td style="text-align:left;">
36
</td>
<td style="text-align:right;">
4.319
</td>
<td style="text-align:right;">
428.46
</td>
<td style="text-align:right;">
111.91
</td>
<td style="text-align:right;">
283.9
</td>
<td style="text-align:right;">
24.314
</td>
<td style="text-align:right;">
1.72
</td>
<td style="text-align:right;">
1.50
</td>
<td style="text-align:right;">
-48052.33
</td>
<td style="text-align:right;">
-5.73
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
2.91
</td>
<td style="text-align:right;">
8.65
</td>
<td style="text-align:right;">
3.130
</td>
</tr>
</tbody>
</table>
<p><strong>Selección de descriptores</strong></p>
<ul>
<li>División set de entrenamiento y set de prueba</li>
</ul>
<p>Los investigadores dividieron el conjunto de datos aleatoriamente en dos grupos: un conjunto de entrenamiento, que consta de treinta moléculas, se utilizó para construir el modelo cuantitativo. Las moléculas restantes (2, 3, 10, 11, 17 y 18) se reservaron para evaluar el rendimiento del modelo propuesto en un conjunto de prueba.</p>
<ul>
<li>Análisis PCA</li>
</ul>
<p>Se empleó el análisis de componentes principales (PCA) para evaluar la no linealidad y la multicolinealidad entre las variables, y para identificar aquellos descriptores que presentaran correlaciones significativas con la actividad.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb3-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:kableExtra&#39;:
## 
##     group_rows</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-1" tabindex="-1"></a><span class="co"># Seleccionar columnas numéricas</span></span>
<span id="cb8-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-2" tabindex="-1"></a>variables_pca <span class="ot">&lt;-</span> Valores_Parametros_Tiadiazoles <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-3" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric)</span>
<span id="cb8-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-4" tabindex="-1"></a></span>
<span id="cb8-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-5" tabindex="-1"></a><span class="co"># Excluir pIC50</span></span>
<span id="cb8-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-6" tabindex="-1"></a><span class="co">#variables_pca$pIC50 &lt;- NULL</span></span>
<span id="cb8-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-7" tabindex="-1"></a></span>
<span id="cb8-8"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-8" tabindex="-1"></a><span class="co"># Realizar PCA</span></span>
<span id="cb8-9"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-9" tabindex="-1"></a>resultado_pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(variables_pca, <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-10"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-10" tabindex="-1"></a></span>
<span id="cb8-11"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-11" tabindex="-1"></a><span class="co"># Resumen PCA</span></span>
<span id="cb8-12"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb8-12" tabindex="-1"></a><span class="fu">summary</span>(resultado_pca)</span></code></pre></div>
<pre><code>## Importance of components:
##                           PC1    PC2    PC3    PC4     PC5     PC6     PC7
## Standard deviation     2.2128 1.5609 1.5204 1.1800 0.83140 0.73144 0.63436
## Proportion of Variance 0.3767 0.1874 0.1778 0.1071 0.05317 0.04115 0.03095
## Cumulative Proportion  0.3767 0.5641 0.7419 0.8490 0.90217 0.94333 0.97428
##                            PC8     PC9    PC10    PC11    PC12     PC13
## Standard deviation     0.49181 0.27554 0.12256 0.02822 0.02591 0.004796
## Proportion of Variance 0.01861 0.00584 0.00116 0.00006 0.00005 0.000000
## Cumulative Proportion  0.99289 0.99873 0.99989 0.99995 1.00000 1.000000</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb10-1" tabindex="-1"></a><span class="co"># Visualizar PCA</span></span>
<span id="cb10-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb10-2" tabindex="-1"></a><span class="fu">biplot</span>(resultado_pca)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>En base a los resultados del análisis de componentes principales (PCA), podemos concluir que los primeros cinco componentes principales (PC1 a PC5) capturan aproximadamente el 90.22% de la varianza total en los datos. Estos componentes tienen desviaciones estándar significativas y explican una cantidad sustancial de la variabilidad. Por otro lado, los componentes PC6 a PC13, con desviaciones estándar más pequeñas y proporciones de varianza muy bajas, parecen tener una contribución marginal y podrían ser excluidos para simplificar aún más el modelo sin comprometer la representación esencial de los datos.</p>
<p>Es importante destacar que en este análisis se incluyó la actividad biológica, para explorar las relaciones entre la actividad y los descriptores en el mismo espacio de componentes principales, permitiendo comprender las relaciones entre los descriptores y la actividad biológica. Sin embargo, si se busca un enfoque diferente, como la reducción de dimensionalidad y la exploración de patrones en los descriptores moleculares por sí mismos, es posible realizar el PCA sin incluir la actividad biológica. La elección de incluir o excluir esta variable debe basarse en los objetivos específicos de la investigación y las necesidades del análisis.</p>
<ul>
<li>Matriz de correlación</li>
</ul>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb11-1" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code></pre></div>
<pre><code>## corrplot 0.92 loaded</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-1" tabindex="-1"></a><span class="co"># Seleccionar columnas numéricas</span></span>
<span id="cb13-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-2" tabindex="-1"></a>variables_matriz_de_correlacion <span class="ot">&lt;-</span> Valores_Parametros_Tiadiazoles <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-3" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric)</span>
<span id="cb13-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-4" tabindex="-1"></a></span>
<span id="cb13-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-5" tabindex="-1"></a><span class="co"># Calcular matriz de correlación </span></span>
<span id="cb13-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-6" tabindex="-1"></a>matriz_correlacion <span class="ot">&lt;-</span> <span class="fu">cor</span>(variables_matriz_de_correlacion)</span>
<span id="cb13-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-7" tabindex="-1"></a></span>
<span id="cb13-8"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-8" tabindex="-1"></a><span class="co"># Redondear la matriz de correlación a 3 decimales</span></span>
<span id="cb13-9"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-9" tabindex="-1"></a>matriz_correlacion_3d<span class="ot">&lt;-</span> <span class="fu">round</span>(matriz_correlacion, <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb13-10"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-10" tabindex="-1"></a></span>
<span id="cb13-11"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-11" tabindex="-1"></a><span class="co"># Mostrar datos</span></span>
<span id="cb13-12"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb13-12" tabindex="-1"></a><span class="fu">kable</span>(matriz_correlacion_3d, <span class="at">format =</span> <span class="st">&quot;html&quot;</span>, <span class="at">table.attr =</span> <span class="st">&#39;style=&quot;font-size: 60%;&quot;&#39;</span>)</span></code></pre></div>
<table style="font-size: 60%;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
pIC50
</th>
<th style="text-align:right;">
MW
</th>
<th style="text-align:right;">
MR
</th>
<th style="text-align:right;">
MV
</th>
<th style="text-align:right;">
Pc
</th>
<th style="text-align:right;">
nn
</th>
<th style="text-align:right;">
D
</th>
<th style="text-align:right;">
Et
</th>
<th style="text-align:right;">
Ehomo
</th>
<th style="text-align:right;">
Elumo
</th>
<th style="text-align:right;">
ΔE
</th>
<th style="text-align:right;">
µµ
</th>
<th style="text-align:right;">
logP
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
pIC50
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
-0.033
</td>
<td style="text-align:right;">
-0.167
</td>
<td style="text-align:right;">
-0.022
</td>
<td style="text-align:right;">
0.184
</td>
<td style="text-align:right;">
-0.231
</td>
<td style="text-align:right;">
0.011
</td>
<td style="text-align:right;">
-0.167
</td>
<td style="text-align:right;">
-0.423
</td>
<td style="text-align:right;">
0.219
</td>
<td style="text-align:right;">
0.614
</td>
<td style="text-align:right;">
-0.159
</td>
<td style="text-align:right;">
0.416
</td>
</tr>
<tr>
<td style="text-align:left;">
MW
</td>
<td style="text-align:right;">
-0.033
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.796
</td>
<td style="text-align:right;">
0.695
</td>
<td style="text-align:right;">
-0.290
</td>
<td style="text-align:right;">
0.142
</td>
<td style="text-align:right;">
0.177
</td>
<td style="text-align:right;">
-0.446
</td>
<td style="text-align:right;">
0.248
</td>
<td style="text-align:right;">
0.099
</td>
<td style="text-align:right;">
-0.215
</td>
<td style="text-align:right;">
0.379
</td>
<td style="text-align:right;">
0.364
</td>
</tr>
<tr>
<td style="text-align:left;">
MR
</td>
<td style="text-align:right;">
-0.167
</td>
<td style="text-align:right;">
0.796
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.837
</td>
<td style="text-align:right;">
-0.722
</td>
<td style="text-align:right;">
0.242
</td>
<td style="text-align:right;">
-0.234
</td>
<td style="text-align:right;">
0.149
</td>
<td style="text-align:right;">
0.612
</td>
<td style="text-align:right;">
0.259
</td>
<td style="text-align:right;">
-0.517
</td>
<td style="text-align:right;">
0.582
</td>
<td style="text-align:right;">
0.313
</td>
</tr>
<tr>
<td style="text-align:left;">
MV
</td>
<td style="text-align:right;">
-0.022
</td>
<td style="text-align:right;">
0.695
</td>
<td style="text-align:right;">
0.837
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
-0.756
</td>
<td style="text-align:right;">
-0.328
</td>
<td style="text-align:right;">
-0.583
</td>
<td style="text-align:right;">
0.135
</td>
<td style="text-align:right;">
0.382
</td>
<td style="text-align:right;">
0.168
</td>
<td style="text-align:right;">
-0.320
</td>
<td style="text-align:right;">
0.455
</td>
<td style="text-align:right;">
0.354
</td>
</tr>
<tr>
<td style="text-align:left;">
Pc
</td>
<td style="text-align:right;">
0.184
</td>
<td style="text-align:right;">
-0.290
</td>
<td style="text-align:right;">
-0.722
</td>
<td style="text-align:right;">
-0.756
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.097
</td>
<td style="text-align:right;">
0.702
</td>
<td style="text-align:right;">
-0.608
</td>
<td style="text-align:right;">
-0.677
</td>
<td style="text-align:right;">
-0.285
</td>
<td style="text-align:right;">
0.572
</td>
<td style="text-align:right;">
-0.523
</td>
<td style="text-align:right;">
-0.098
</td>
</tr>
<tr>
<td style="text-align:left;">
nn
</td>
<td style="text-align:right;">
-0.231
</td>
<td style="text-align:right;">
0.142
</td>
<td style="text-align:right;">
0.242
</td>
<td style="text-align:right;">
-0.328
</td>
<td style="text-align:right;">
0.097
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.630
</td>
<td style="text-align:right;">
0.015
</td>
<td style="text-align:right;">
0.377
</td>
<td style="text-align:right;">
0.169
</td>
<td style="text-align:right;">
-0.309
</td>
<td style="text-align:right;">
0.200
</td>
<td style="text-align:right;">
-0.071
</td>
</tr>
<tr>
<td style="text-align:left;">
D
</td>
<td style="text-align:right;">
0.011
</td>
<td style="text-align:right;">
0.177
</td>
<td style="text-align:right;">
-0.234
</td>
<td style="text-align:right;">
-0.583
</td>
<td style="text-align:right;">
0.702
</td>
<td style="text-align:right;">
0.630
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
-0.677
</td>
<td style="text-align:right;">
-0.225
</td>
<td style="text-align:right;">
-0.085
</td>
<td style="text-align:right;">
0.197
</td>
<td style="text-align:right;">
-0.189
</td>
<td style="text-align:right;">
-0.057
</td>
</tr>
<tr>
<td style="text-align:left;">
Et
</td>
<td style="text-align:right;">
-0.167
</td>
<td style="text-align:right;">
-0.446
</td>
<td style="text-align:right;">
0.149
</td>
<td style="text-align:right;">
0.135
</td>
<td style="text-align:right;">
-0.608
</td>
<td style="text-align:right;">
0.015
</td>
<td style="text-align:right;">
-0.677
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.382
</td>
<td style="text-align:right;">
0.163
</td>
<td style="text-align:right;">
-0.319
</td>
<td style="text-align:right;">
0.180
</td>
<td style="text-align:right;">
-0.227
</td>
</tr>
<tr>
<td style="text-align:left;">
Ehomo
</td>
<td style="text-align:right;">
-0.423
</td>
<td style="text-align:right;">
0.248
</td>
<td style="text-align:right;">
0.612
</td>
<td style="text-align:right;">
0.382
</td>
<td style="text-align:right;">
-0.677
</td>
<td style="text-align:right;">
0.377
</td>
<td style="text-align:right;">
-0.225
</td>
<td style="text-align:right;">
0.382
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.459
</td>
<td style="text-align:right;">
-0.818
</td>
<td style="text-align:right;">
0.706
</td>
<td style="text-align:right;">
-0.164
</td>
</tr>
<tr>
<td style="text-align:left;">
Elumo
</td>
<td style="text-align:right;">
0.219
</td>
<td style="text-align:right;">
0.099
</td>
<td style="text-align:right;">
0.259
</td>
<td style="text-align:right;">
0.168
</td>
<td style="text-align:right;">
-0.285
</td>
<td style="text-align:right;">
0.169
</td>
<td style="text-align:right;">
-0.085
</td>
<td style="text-align:right;">
0.163
</td>
<td style="text-align:right;">
0.459
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.135
</td>
<td style="text-align:right;">
0.294
</td>
<td style="text-align:right;">
0.155
</td>
</tr>
<tr>
<td style="text-align:left;">
ΔE
</td>
<td style="text-align:right;">
0.614
</td>
<td style="text-align:right;">
-0.215
</td>
<td style="text-align:right;">
-0.517
</td>
<td style="text-align:right;">
-0.320
</td>
<td style="text-align:right;">
0.572
</td>
<td style="text-align:right;">
-0.309
</td>
<td style="text-align:right;">
0.197
</td>
<td style="text-align:right;">
-0.319
</td>
<td style="text-align:right;">
-0.818
</td>
<td style="text-align:right;">
0.135
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
-0.598
</td>
<td style="text-align:right;">
0.283
</td>
</tr>
<tr>
<td style="text-align:left;">
µµ
</td>
<td style="text-align:right;">
-0.159
</td>
<td style="text-align:right;">
0.379
</td>
<td style="text-align:right;">
0.582
</td>
<td style="text-align:right;">
0.455
</td>
<td style="text-align:right;">
-0.523
</td>
<td style="text-align:right;">
0.200
</td>
<td style="text-align:right;">
-0.189
</td>
<td style="text-align:right;">
0.180
</td>
<td style="text-align:right;">
0.706
</td>
<td style="text-align:right;">
0.294
</td>
<td style="text-align:right;">
-0.598
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
-0.011
</td>
</tr>
<tr>
<td style="text-align:left;">
logP
</td>
<td style="text-align:right;">
0.416
</td>
<td style="text-align:right;">
0.364
</td>
<td style="text-align:right;">
0.313
</td>
<td style="text-align:right;">
0.354
</td>
<td style="text-align:right;">
-0.098
</td>
<td style="text-align:right;">
-0.071
</td>
<td style="text-align:right;">
-0.057
</td>
<td style="text-align:right;">
-0.227
</td>
<td style="text-align:right;">
-0.164
</td>
<td style="text-align:right;">
0.155
</td>
<td style="text-align:right;">
0.283
</td>
<td style="text-align:right;">
-0.011
</td>
<td style="text-align:right;">
1.000
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb14-1" tabindex="-1"></a><span class="co"># Visualizar matriz de correlación</span></span>
<span id="cb14-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb14-2" tabindex="-1"></a><span class="fu">corrplot</span>(matriz_correlacion, <span class="at">method =</span> <span class="st">&quot;color&quot;</span>, <span class="at">type =</span> <span class="st">&quot;lower&quot;</span>, <span class="at">tl.cex =</span> <span class="fl">0.7</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>La matriz de correlación indica que existen correlaciones moderadas entre algunas variables, pero no hay una correlación extrema que sugiera una multicolinealidad severa. Es decir, las variables están relacionadas de manera moderada, pero no en exceso, lo que permite considerar múltiples variables en un modelo sin preocuparse por una colinealidad extrema.</p>
<p><strong>Construcción del modelo</strong></p>
<ul>
<li>Regresión lineal múltiple del artículo</li>
</ul>
<p>En el artículo, los investigadores utilizaron los descriptores obtenidos para desarrollar un modelo lineal con el propósito de predecir los efectos de los sustituyentes sobre la actividad antileishmania de 30 derivados de tiadiazol (conjunto de entrenamiento) mediante la selección hacia atrás en el MLR. La mejor combinación lineal obtenida incluye tres descriptores seleccionados: la energía Elumo, la energía Ehomo y el coeficiente de partición octanol/agua logP.</p>
<p>Se realizaron múltiples regresiones lineales utilizando el software XLSTAT versión 2013 para predecir los efectos sobre la actividad antileishmania, como se describe en el artículo. Las ecuaciones de los modelos se justifican principalmente por el coeficiente de correlación (R), el error cuadrático medio (MSE), la estadística F de Fisher y el nivel de significancia (valor p). Los resultados por parte de los investigadores en el artículo se muestran a continuación:</p>
<p>Ecuación:
<span class="math display">\[pIC_{50} = 2.0453-0.6673 E_{homo} + 0.7821 E_{lumo} + 0.1898 logP\]</span></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb15-1" tabindex="-1"></a>informacion_modeloMLR_articulo <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb15-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb15-2" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">c</span>(<span class="st">&quot;N&quot;</span>, <span class="st">&quot;R&quot;</span>, <span class="st">&quot;MSE&quot;</span>, <span class="st">&quot;F&quot;</span>, <span class="st">&quot;p-valor&quot;</span>),</span>
<span id="cb15-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb15-3" tabindex="-1"></a>  <span class="at">Valor =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="fl">0.750</span>, <span class="fl">0.119</span>, <span class="fl">11.43</span>, <span class="st">&quot;&lt;0.0001&quot;</span>)</span>
<span id="cb15-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb15-4" tabindex="-1"></a>)</span>
<span id="cb15-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb15-5" tabindex="-1"></a></span>
<span id="cb15-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb15-6" tabindex="-1"></a><span class="co"># Mostrar información</span></span>
<span id="cb15-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb15-7" tabindex="-1"></a><span class="fu">kable</span>(informacion_modeloMLR_articulo, <span class="at">align =</span> <span class="st">&quot;c&quot;</span>)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:center;">
Variable
</th>
<th style="text-align:center;">
Valor
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
30
</td>
</tr>
<tr>
<td style="text-align:center;">
R
</td>
<td style="text-align:center;">
0.75
</td>
</tr>
<tr>
<td style="text-align:center;">
MSE
</td>
<td style="text-align:center;">
0.119
</td>
</tr>
<tr>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
11.43
</td>
</tr>
<tr>
<td style="text-align:center;">
p-valor
</td>
<td style="text-align:center;">
&lt;0.0001
</td>
</tr>
</tbody>
</table>
<ul>
<li>Regresión lineal múltiple de nuestro caso práctico</li>
</ul>
<p>En nuestro caso práctico, optamos por realizar el análisis y desarrollo del modelo directamente en RStudio, una plataforma ampliamente utilizada para estadísticas y análisis de datos. A continuación, presentaremos el procedimiento.</p>
<ul>
<li>Conjunto de datos para entrenamiento</li>
</ul>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb16-1" tabindex="-1"></a><span class="co"># Cargar datos</span></span>
<span id="cb16-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb16-2" tabindex="-1"></a>Set_Entrenamiento <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">&quot;Set_Entrenamiento.xlsx&quot;</span>)</span>
<span id="cb16-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb16-3" tabindex="-1"></a></span>
<span id="cb16-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb16-4" tabindex="-1"></a><span class="co"># Mostrar datos</span></span>
<span id="cb16-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb16-5" tabindex="-1"></a><span class="fu">kable</span>(Set_Entrenamiento)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:right;">
N
</th>
<th style="text-align:right;">
pIC50
</th>
<th style="text-align:right;">
Ehomo
</th>
<th style="text-align:right;">
Elumo
</th>
<th style="text-align:right;">
logP
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.932
</td>
<td style="text-align:right;">
-6.59
</td>
<td style="text-align:right;">
-2.84
</td>
<td style="text-align:right;">
1.844
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
4.969
</td>
<td style="text-align:right;">
-6.70
</td>
<td style="text-align:right;">
-2.85
</td>
<td style="text-align:right;">
2.402
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
4.717
</td>
<td style="text-align:right;">
-6.38
</td>
<td style="text-align:right;">
-3.08
</td>
<td style="text-align:right;">
1.825
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4.921
</td>
<td style="text-align:right;">
-6.70
</td>
<td style="text-align:right;">
-2.88
</td>
<td style="text-align:right;">
2.199
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
4.882
</td>
<td style="text-align:right;">
-6.65
</td>
<td style="text-align:right;">
-2.87
</td>
<td style="text-align:right;">
2.534
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
4.602
</td>
<td style="text-align:right;">
-6.37
</td>
<td style="text-align:right;">
-2.48
</td>
<td style="text-align:right;">
3.210
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
4.463
</td>
<td style="text-align:right;">
-6.69
</td>
<td style="text-align:right;">
-2.93
</td>
<td style="text-align:right;">
3.768
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
4.549
</td>
<td style="text-align:right;">
-6.61
</td>
<td style="text-align:right;">
-2.93
</td>
<td style="text-align:right;">
3.191
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
4.624
</td>
<td style="text-align:right;">
-6.68
</td>
<td style="text-align:right;">
-2.96
</td>
<td style="text-align:right;">
3.565
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
4.608
</td>
<td style="text-align:right;">
-6.65
</td>
<td style="text-align:right;">
-2.96
</td>
<td style="text-align:right;">
3.900
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
4.983
</td>
<td style="text-align:right;">
-6.25
</td>
<td style="text-align:right;">
-2.81
</td>
<td style="text-align:right;">
3.856
</td>
</tr>
<tr>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
4.693
</td>
<td style="text-align:right;">
-6.32
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
3.039
</td>
</tr>
<tr>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
4.592
</td>
<td style="text-align:right;">
-6.35
</td>
<td style="text-align:right;">
-2.87
</td>
<td style="text-align:right;">
3.756
</td>
</tr>
<tr>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
5.029
</td>
<td style="text-align:right;">
-5.81
</td>
<td style="text-align:right;">
-1.95
</td>
<td style="text-align:right;">
2.956
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
4.797
</td>
<td style="text-align:right;">
-6.42
</td>
<td style="text-align:right;">
-2.90
</td>
<td style="text-align:right;">
2.984
</td>
</tr>
<tr>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
3.983
</td>
<td style="text-align:right;">
-6.25
</td>
<td style="text-align:right;">
-2.94
</td>
<td style="text-align:right;">
2.784
</td>
</tr>
<tr>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
3.955
</td>
<td style="text-align:right;">
-5.75
</td>
<td style="text-align:right;">
-2.84
</td>
<td style="text-align:right;">
1.894
</td>
</tr>
<tr>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
4.638
</td>
<td style="text-align:right;">
-5.75
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
2.414
</td>
</tr>
<tr>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
4.482
</td>
<td style="text-align:right;">
-5.73
</td>
<td style="text-align:right;">
-2.80
</td>
<td style="text-align:right;">
2.753
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
5.000
</td>
<td style="text-align:right;">
-5.73
</td>
<td style="text-align:right;">
-2.12
</td>
<td style="text-align:right;">
3.239
</td>
</tr>
<tr>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
4.959
</td>
<td style="text-align:right;">
-5.71
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
3.656
</td>
</tr>
<tr>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
4.482
</td>
<td style="text-align:right;">
-5.20
</td>
<td style="text-align:right;">
-1.92
</td>
<td style="text-align:right;">
3.557
</td>
</tr>
<tr>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
5.046
</td>
<td style="text-align:right;">
-5.73
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
4.288
</td>
</tr>
<tr>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
4.100
</td>
<td style="text-align:right;">
-5.72
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
4.162
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
4.022
</td>
<td style="text-align:right;">
-5.76
</td>
<td style="text-align:right;">
-2.83
</td>
<td style="text-align:right;">
2.555
</td>
</tr>
<tr>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
4.032
</td>
<td style="text-align:right;">
-5.77
</td>
<td style="text-align:right;">
-2.83
</td>
<td style="text-align:right;">
2.392
</td>
</tr>
<tr>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
3.155
</td>
<td style="text-align:right;">
-5.42
</td>
<td style="text-align:right;">
-3.00
</td>
<td style="text-align:right;">
0.821
</td>
</tr>
<tr>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
3.222
</td>
<td style="text-align:right;">
-5.57
</td>
<td style="text-align:right;">
-2.81
</td>
<td style="text-align:right;">
0.927
</td>
</tr>
<tr>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
4.143
</td>
<td style="text-align:right;">
-5.92
</td>
<td style="text-align:right;">
-2.86
</td>
<td style="text-align:right;">
3.579
</td>
</tr>
<tr>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
4.319
</td>
<td style="text-align:right;">
-5.73
</td>
<td style="text-align:right;">
-2.82
</td>
<td style="text-align:right;">
3.130
</td>
</tr>
</tbody>
</table>
<ul>
<li>Generación modelo MLR</li>
</ul>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb17-1" tabindex="-1"></a><span class="co"># Excluir columna N (columna de identificacón de las moléculas)</span></span>
<span id="cb17-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb17-2" tabindex="-1"></a>Set_Entrenamiento<span class="sc">$</span>N <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb17-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb17-3" tabindex="-1"></a></span>
<span id="cb17-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb17-4" tabindex="-1"></a><span class="co"># Ajustar el modelo de regresión múltiple</span></span>
<span id="cb17-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb17-5" tabindex="-1"></a>modeloMLR <span class="ot">&lt;-</span> <span class="fu">lm</span>(pIC50 <span class="sc">~</span> Ehomo <span class="sc">+</span> Elumo <span class="sc">+</span> logP, <span class="at">data =</span> Set_Entrenamiento)</span>
<span id="cb17-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb17-6" tabindex="-1"></a></span>
<span id="cb17-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb17-7" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb17-8"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb17-8" tabindex="-1"></a><span class="fu">summary</span>(modeloMLR)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = pIC50 ~ Ehomo + Elumo + logP, data = Set_Entrenamiento)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.51750 -0.28208 -0.00307  0.23097  0.61467 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.03235    0.93236   2.180 0.038519 *  
## Ehomo       -0.66714    0.16179  -4.123 0.000339 ***
## Elumo        0.77764    0.26150   2.974 0.006271 ** 
## logP         0.19026    0.07651   2.487 0.019636 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3449 on 26 degrees of freedom
## Multiple R-squared:  0.5592, Adjusted R-squared:  0.5083 
## F-statistic: 10.99 on 3 and 26 DF,  p-value: 7.63e-05</code></pre>
<p>La ecuación resultante del modelo es:</p>
<p><span class="math display">\[pIC_{50} = 2.0323-0.6671 E_{homo} + 0.7776 E_{lumo} + 0.1903 logP\]</span></p>
<p>Para una comparación directa de resultados, generamos la misma información que los investigadores en el estudio, como se muestra a continuación:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-1" tabindex="-1"></a><span class="co"># Número de compuestos (N)</span></span>
<span id="cb19-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-2" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">length</span>(modeloMLR<span class="sc">$</span>fitted.values)</span>
<span id="cb19-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-3" tabindex="-1"></a><span class="co"># Coeficiente de correlación (R)</span></span>
<span id="cb19-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-4" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">summary</span>(modeloMLR)<span class="sc">$</span>r.squared)</span>
<span id="cb19-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-5" tabindex="-1"></a><span class="co"># Error cuadrático medio (MSE)</span></span>
<span id="cb19-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-6" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> <span class="fu">summary</span>(modeloMLR)<span class="sc">$</span>sigma<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb19-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-7" tabindex="-1"></a><span class="co"># Criterio de Fisher (F)</span></span>
<span id="cb19-8"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-8" tabindex="-1"></a>Fisher <span class="ot">&lt;-</span> <span class="fu">summary</span>(modeloMLR)<span class="sc">$</span>fstatistic[<span class="dv">1</span>]</span>
<span id="cb19-9"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-9" tabindex="-1"></a><span class="co"># Nivel de significancia (p-valor)</span></span>
<span id="cb19-10"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-10" tabindex="-1"></a>p.valor <span class="ot">&lt;-</span> <span class="fu">pf</span>(Fisher, <span class="fu">summary</span>(modeloMLR)<span class="sc">$</span>fstatistic[<span class="dv">2</span>], <span class="fu">summary</span>(modeloMLR)<span class="sc">$</span>fstatistic[<span class="dv">3</span>], <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-11"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-11" tabindex="-1"></a></span>
<span id="cb19-12"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-12" tabindex="-1"></a><span class="co"># Dataframe con la información</span></span>
<span id="cb19-13"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-13" tabindex="-1"></a>informacion_modeloMLR <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-14"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-14" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">c</span>(<span class="st">&quot;N&quot;</span>, <span class="st">&quot;R&quot;</span>, <span class="st">&quot;MSE&quot;</span>, <span class="st">&quot;F&quot;</span>, <span class="st">&quot;p-valor&quot;</span>),</span>
<span id="cb19-15"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-15" tabindex="-1"></a>  <span class="at">Valor =</span> <span class="fu">c</span>(N, R, MSE, Fisher, p.valor)</span>
<span id="cb19-16"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-16" tabindex="-1"></a>)</span>
<span id="cb19-17"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-17" tabindex="-1"></a><span class="co"># Mostrar información</span></span>
<span id="cb19-18"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb19-18" tabindex="-1"></a><span class="fu">kable</span>(informacion_modeloMLR, <span class="at">align =</span> <span class="st">&quot;c&quot;</span>)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:center;">
Variable
</th>
<th style="text-align:center;">
Valor
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
30.0000000
</td>
</tr>
<tr>
<td style="text-align:center;">
R
</td>
<td style="text-align:center;">
0.7477869
</td>
</tr>
<tr>
<td style="text-align:center;">
MSE
</td>
<td style="text-align:center;">
0.1189792
</td>
</tr>
<tr>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
10.9938985
</td>
</tr>
<tr>
<td style="text-align:center;">
p-valor
</td>
<td style="text-align:center;">
0.0000763
</td>
</tr>
</tbody>
</table>
<ul>
<li>Comparación de resultados</li>
</ul>
<p>Ecuación generada con XLSTAT:
<span class="math display">\[pIC_{50} = 2.0453-0.6673 E_{homo} + 0.7821 E_{lumo} + 0.1898 logP\]</span></p>
<p>Ecuación generada con Rstudio:
<span class="math display">\[pIC_{50} = 2.0323-0.6671 E_{homo} + 0.7776 E_{lumo} + 0.1903 logP\]</span></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb20-1" tabindex="-1"></a><span class="co"># Combinar tablas por la columna &#39;Variable&#39;</span></span>
<span id="cb20-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb20-2" tabindex="-1"></a>tabla_comparativa <span class="ot">&lt;-</span> <span class="fu">merge</span>(informacion_modeloMLR_articulo, informacion_modeloMLR, <span class="at">by =</span> <span class="st">&quot;Variable&quot;</span>, <span class="at">all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb20-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb20-3" tabindex="-1"></a></span>
<span id="cb20-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb20-4" tabindex="-1"></a><span class="co"># Renombra las columnas para mayor claridad</span></span>
<span id="cb20-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb20-5" tabindex="-1"></a><span class="fu">colnames</span>(tabla_comparativa) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Variable&quot;</span>, <span class="st">&quot;Valor XLSTAT&quot;</span>, <span class="st">&quot;Valor Rstudio&quot;</span>)</span>
<span id="cb20-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb20-6" tabindex="-1"></a></span>
<span id="cb20-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb20-7" tabindex="-1"></a><span class="co"># Muestra la tabla comparativa</span></span>
<span id="cb20-8"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb20-8" tabindex="-1"></a><span class="fu">kable</span>(tabla_comparativa, <span class="at">align =</span> <span class="st">&quot;c&quot;</span>)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:center;">
Variable
</th>
<th style="text-align:center;">
Valor XLSTAT
</th>
<th style="text-align:center;">
Valor Rstudio
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
11.43
</td>
<td style="text-align:center;">
10.9938985
</td>
</tr>
<tr>
<td style="text-align:center;">
MSE
</td>
<td style="text-align:center;">
0.119
</td>
<td style="text-align:center;">
0.1189792
</td>
</tr>
<tr>
<td style="text-align:center;">
N
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
30.0000000
</td>
</tr>
<tr>
<td style="text-align:center;">
p-valor
</td>
<td style="text-align:center;">
&lt;0.0001
</td>
<td style="text-align:center;">
0.0000763
</td>
</tr>
<tr>
<td style="text-align:center;">
R
</td>
<td style="text-align:center;">
0.75
</td>
<td style="text-align:center;">
0.7477869
</td>
</tr>
</tbody>
</table>
<p><strong>Validación del modelo</strong></p>
<ul>
<li>Validación Interna de nuestro caso práctico</li>
</ul>
<p>Se llevó a cabo la validación cruzada interna dejando uno fuera (también conocida como “leave-one-out cross-validation” o LOOCV). LOOCV es un caso especial de validación cruzada en el que se entrena el modelo con todos los datos excepto uno y se evalúa en ese único punto excluido. Este proceso se repite para cada punto de datos, lo que garantiza que cada punto se excluya una vez.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb21-1" tabindex="-1"></a><span class="fu">library</span>(data.table)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;data.table&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     between, first, last</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb24-1" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code></pre></div>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-1" tabindex="-1"></a><span class="co"># Excluir columna N (columna de identificación de las moléculas)</span></span>
<span id="cb27-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-2" tabindex="-1"></a>Set_Entrenamiento<span class="sc">$</span>N <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb27-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-3" tabindex="-1"></a></span>
<span id="cb27-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-4" tabindex="-1"></a><span class="co"># Crear un controlador para la validación cruzada dejando uno fuera</span></span>
<span id="cb27-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-5" tabindex="-1"></a>control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">&quot;LOOCV&quot;</span>)</span>
<span id="cb27-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-6" tabindex="-1"></a></span>
<span id="cb27-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-7" tabindex="-1"></a><span class="co"># Ajustar el modelo de regresión múltiple con LOOCV</span></span>
<span id="cb27-8"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-8" tabindex="-1"></a>modeloMLR_cv <span class="ot">&lt;-</span> <span class="fu">train</span>(pIC50 <span class="sc">~</span> Ehomo <span class="sc">+</span> Elumo <span class="sc">+</span> logP, <span class="at">data =</span> Set_Entrenamiento, <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">trControl =</span> control)</span>
<span id="cb27-9"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-9" tabindex="-1"></a></span>
<span id="cb27-10"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-10" tabindex="-1"></a><span class="co"># Ver los resultados</span></span>
<span id="cb27-11"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb27-11" tabindex="-1"></a><span class="fu">print</span>(modeloMLR_cv)</span></code></pre></div>
<pre><code>## Linear Regression 
## 
## 30 samples
##  3 predictor
## 
## No pre-processing
## Resampling: Leave-One-Out Cross-Validation 
## Summary of sample sizes: 29, 29, 29, 29, 29, 29, ... 
## Resampling results:
## 
##   RMSE       Rsquared   MAE      
##   0.3766402  0.4015121  0.3276817
## 
## Tuning parameter &#39;intercept&#39; was held constant at a value of TRUE</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb29-1" tabindex="-1"></a><span class="fu">summary</span>(modeloMLR_cv<span class="sc">$</span>finalModel)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = .outcome ~ ., data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.51750 -0.28208 -0.00307  0.23097  0.61467 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.03235    0.93236   2.180 0.038519 *  
## Ehomo       -0.66714    0.16179  -4.123 0.000339 ***
## Elumo        0.77764    0.26150   2.974 0.006271 ** 
## logP         0.19026    0.07651   2.487 0.019636 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3449 on 26 degrees of freedom
## Multiple R-squared:  0.5592, Adjusted R-squared:  0.5083 
## F-statistic: 10.99 on 3 and 26 DF,  p-value: 7.63e-05</code></pre>
<p>Un buen valor de Rcv (Coeficiente de correlación en la validacion cruzada interna) de diez indica que el modelo tiene robustez y alto poder predictivo interno en el conjunto de datos utilizado.</p>
<p>Sin embargo, es importante tener en cuenta que el valor de Rcv no siempre está correlacionado con el poder predictivo real de un modelo QSAR en sustancias químicas nuevas. Esto significa que Rcv podría no ser una estimación confiable del poder predictivo del modelo para todas las sustancias químicas. Para una evaluación más confiable del poder predictivo, se requiere un conjunto de validación externa que no se haya utilizado en el desarrollo del modelo.</p>
<p>Para mejorar la capacidad predictiva de los modelos QSAR, se calculan un conjunto de métricas llamadas “métricas <span class="math inline">\(r²_{m}\)</span>”. Estas métricas evalúan qué tan cerca están las predicciones del modelo de los valores reales observados en los datos. En la actualidad, se calculan dos versiones de estas métricas: una que llamamos “<span class="math inline">\(r²_{m}\)</span>” y otra llamada “<span class="math inline">\(\Delta r²_{m}\)</span>”. Ambas se utilizan tanto en la validación interna (conjunto de entrenamiento) como en la validación externa (conjunto de prueba) de los modelos QSAR.</p>
<p>Para considerar que un modelo QSAR es aceptable, el valor de “<span class="math inline">\(\bar{r²_{m}}\)</span>” debe ser mayor que 0.5, lo que indica una buena concordancia entre las predicciones y los valores reales. Además, el valor de “<span class="math inline">\(\Delta r²_{m}\)</span>” debe ser menor que 0.2, lo que sugiere una pequeña diferencia entre las dos versiones de métricas. Estos criterios son importantes para evaluar la calidad de un modelo QSAR y su capacidad para predecir de manera precisa.</p>
<p>A continuación se muestran los cálculos de Rvc, y las métricas <span class="math inline">\(r²_{m}\)</span>:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-1" tabindex="-1"></a><span class="co"># Obtener las predicciones del modelo para el conjunto de entrenamiento</span></span>
<span id="cb31-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-2" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modeloMLR_cv, Set_Entrenamiento)</span>
<span id="cb31-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-3" tabindex="-1"></a></span>
<span id="cb31-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-4" tabindex="-1"></a><span class="co"># Obtener el Rcv (Coeficiente de correlación) </span></span>
<span id="cb31-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-5" tabindex="-1"></a>Rcv <span class="ot">&lt;-</span> <span class="fu">cor</span>(predicciones, Set_Entrenamiento<span class="sc">$</span>pIC50)</span>
<span id="cb31-6"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-6" tabindex="-1"></a></span>
<span id="cb31-7"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-7" tabindex="-1"></a><span class="co"># Calcular r²m (R cuadrado subíndice m)</span></span>
<span id="cb31-8"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-8" tabindex="-1"></a>r2_m <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>((Set_Entrenamiento<span class="sc">$</span>pIC50 <span class="sc">-</span> predicciones)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">sum</span>((Set_Entrenamiento<span class="sc">$</span>pIC50 <span class="sc">-</span> <span class="fu">mean</span>(Set_Entrenamiento<span class="sc">$</span>pIC50))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb31-9"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-9" tabindex="-1"></a></span>
<span id="cb31-10"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-10" tabindex="-1"></a><span class="co"># Definir el valor de r&#39;²m (valor de referencia o alternativo)</span></span>
<span id="cb31-11"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-11" tabindex="-1"></a>r2_m_ref <span class="ot">&lt;-</span> <span class="fl">0.75</span></span>
<span id="cb31-12"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-12" tabindex="-1"></a></span>
<span id="cb31-13"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-13" tabindex="-1"></a><span class="co"># Calcular la diferencia absoluta entre r²m y r&#39;²m</span></span>
<span id="cb31-14"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-14" tabindex="-1"></a>Delta_r2_m <span class="ot">&lt;-</span> <span class="fu">abs</span>(r2_m <span class="sc">-</span> r2_m_ref)</span>
<span id="cb31-15"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-15" tabindex="-1"></a></span>
<span id="cb31-16"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-16" tabindex="-1"></a><span class="co"># Calcular el promedio de r²m y r&#39;²m</span></span>
<span id="cb31-17"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-17" tabindex="-1"></a>Promedio_r2_m <span class="ot">&lt;-</span> (r2_m <span class="sc">+</span> r2_m_ref) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb31-18"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-18" tabindex="-1"></a></span>
<span id="cb31-19"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-19" tabindex="-1"></a><span class="co"># Tabla con resultados</span></span>
<span id="cb31-20"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-20" tabindex="-1"></a>tabla_resultados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb31-21"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-21" tabindex="-1"></a>  <span class="st">&quot;Medida&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Rcv (Coeficiente de correlación) &quot;</span>, <span class="st">&quot;r²m (R cuadrado subíndice m)&quot;</span>, </span>
<span id="cb31-22"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-22" tabindex="-1"></a>               <span class="st">&quot;r&#39;²m (valor de referencia o alternativo)&quot;</span>, <span class="st">&quot;Δr²m (Diferencia absoluta entre r²m y r&#39;²m)&quot;</span>, </span>
<span id="cb31-23"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-23" tabindex="-1"></a>               <span class="st">&quot;Promedio de r²m y r&#39;²m&quot;</span>),</span>
<span id="cb31-24"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-24" tabindex="-1"></a>  <span class="st">&quot;Valor&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(Rcv, r2_m, r2_m_ref, Delta_r2_m, Promedio_r2_m)</span>
<span id="cb31-25"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-25" tabindex="-1"></a>)</span>
<span id="cb31-26"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-26" tabindex="-1"></a></span>
<span id="cb31-27"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-27" tabindex="-1"></a><span class="co"># Mostrar tabla</span></span>
<span id="cb31-28"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb31-28" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tabla_resultados)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
Medida
</th>
<th style="text-align:right;">
Valor
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Rcv (Coeficiente de correlación)
</td>
<td style="text-align:right;">
0.7477869
</td>
</tr>
<tr>
<td style="text-align:left;">
r²m (R cuadrado subíndice m)
</td>
<td style="text-align:right;">
0.5591853
</td>
</tr>
<tr>
<td style="text-align:left;">
r’²m (valor de referencia o alternativo)
</td>
<td style="text-align:right;">
0.7500000
</td>
</tr>
<tr>
<td style="text-align:left;">
Δr²m (Diferencia absoluta entre r²m y r’²m)
</td>
<td style="text-align:right;">
0.1908147
</td>
</tr>
<tr>
<td style="text-align:left;">
Promedio de r²m y r’²m
</td>
<td style="text-align:right;">
0.6545926
</td>
</tr>
</tbody>
</table>
<ul>
<li>Validación Externa</li>
</ul>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb32-1" tabindex="-1"></a><span class="co"># Cargar datos</span></span>
<span id="cb32-2"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb32-2" tabindex="-1"></a>Set_Prueba <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">&quot;Set_Prueba.xlsx&quot;</span>)</span>
<span id="cb32-3"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb32-3" tabindex="-1"></a></span>
<span id="cb32-4"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb32-4" tabindex="-1"></a><span class="co"># Mostrar datos</span></span>
<span id="cb32-5"><a href="caso-práctico-modelo-qsar-regresión-lineal-múltiple.html#cb32-5" tabindex="-1"></a><span class="fu">kable</span>(Set_Prueba)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:right;">
N
</th>
<th style="text-align:right;">
pIC50
</th>
<th style="text-align:right;">
Ehomo
</th>
<th style="text-align:right;">
Elumo
</th>
<th style="text-align:right;">
logP
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
4.880
</td>
<td style="text-align:right;">
-6.41
</td>
<td style="text-align:right;">
-2.92
</td>
<td style="text-align:right;">
2.402
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
4.581
</td>
<td style="text-align:right;">
-6.69
</td>
<td style="text-align:right;">
-2.88
</td>
<td style="text-align:right;">
2.402
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
4.222
</td>
<td style="text-align:right;">
-6.70
</td>
<td style="text-align:right;">
-2.96
</td>
<td style="text-align:right;">
3.768
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
4.618
</td>
<td style="text-align:right;">
-6.70
</td>
<td style="text-align:right;">
-2.97
</td>
<td style="text-align:right;">
3.768
</td>
</tr>
<tr>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
4.748
</td>
<td style="text-align:right;">
-6.35
</td>
<td style="text-align:right;">
-2.86
</td>
<td style="text-align:right;">
2.825
</td>
</tr>
<tr>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
4.367
</td>
<td style="text-align:right;">
-6.40
</td>
<td style="text-align:right;">
-2.72
</td>
<td style="text-align:right;">
3.956
</td>
</tr>
</tbody>
</table>
<p><strong>Referencias</strong></p>
<ol style="list-style-type: decimal">
<li>Ousaa A, Elidrissi B, Ghamali M, Chtita S, Aouidate A, Bouachrine M, et al. QSAR Study of (5-Nitroheteroaryl-1,3,4-Thiadiazole-2-yl) Piperazinyl Derivatives to Predict New Similar Compounds as Antileishmanial Agents. Adv Phys Chem. 10 de septiembre de 2018;2018:1-10.</li>
<li>Tahghighi A, Hamzeh-Mivehroud M, Asadpour Zeynali K, Foroumadi A, Dastmalchi S. QSAR and docking studies on the (5-nitroheteroaryl-1,3,4-thiadiazole-2-yl) piperazinyl analogs with antileishmanial activity: QSAR and docking study on thiadiazole series as antileishmanial agents. J Chemom. mayo de 2016;30(5):284-93.</li>
<li>Frich M. Gaussian 03 Revisión B.01. Pitts-burgh, California, EE. UU.: Gaussian, Inc.; 2003.</li>
<li>ACDLABS 10. Toronto, Canadá: Advanced Chemistry Development, Inc.; 2015.</li>
</ol>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="validación-del-modelo-qsar.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/YOUR GITHUB USERNAME/YOUR REPO NAME/edit/main/Seccion8.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/YOUR GITHUB USERNAME/YOUR REPO NAME/blob/main/Seccion8.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
